### ISSUE TITLE
[BUG] Z axis does not move when using BLTouch

### ISSUE THREAD

**Issue by Bromim** [FB-G6/Marlin#6]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Firmware for FB-G6 with BLTouch does not move Z axis when setting home position. 
Commenting out the line helped me:
"#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN"
And adding "#define Z_MIN_PROBE_PIN PC4 //Pin 32 is the RAMPS default"
And everything worked.

### Version of Marlin Firmware

Marlin-2.1.2.8rc3

### Printer model

Flyingbear Ghost 6

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/FB-G6/Marlin/files/11712269/Marlin.zip)

**Comment by tarwirdur** [comment]
In which port did you connect the bltouch?

Firmware compiled to connect a bltouch **instead of Z-endstop** (port `Z-` on board  [`PC8` pin]).

There is [page](https://github.com/FB-G6/Marlin/wiki/%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-BLTouch) on wiki (currently in russian language only, sorry)
